### ISSUE TITLE
Naming convention for events

### ISSUE THREAD

**Issue by clayrisser** [Place1/react-native-gtk#13]
We need to have a solid naming convention for events. We've decided that we will approach naming from the JavaScript world. We might want to make a simple table mapping our event names to gtk's signals.

**Comment by Place1** [comment]
Gnome's [how to write a language binding](https://wiki.gnome.org/Projects/GObjectIntrospection/HowToWriteALanguageBinding) says to following the naming conventions of the platform. So we'll use camel case for sure. Something worth debating is gtk names such as `button.on_clicked`, should this become `button.onClicked` or `button.onClick`? What do the `gjs` or `seed` bindings do for reference?

**Comment by clayrisser** [comment]
If we're going to be consistent with our philosophy of development, it would be `onClick`, because we put the JavaScript developer first.

**Comment by Place1** [comment]
That’s true and I argued that point before, but to play devils advocate,
people might assume it’s called onClicked because that’s what gtk calls it
in their docs (people may use that as a resource). In react native buttons
have the onPress prop, not onClick, so there’s that too.
I’m a little worried that choosing anything that’s not “camel case gtk
name” will lead to contributor confusion and hairy debates.

**Comment by clayrisser** [comment]
That's why I think we should create a table that shows the name changes we made.

**Comment by Place1** [comment]
we're moving to use gobject introspection, so this issue no longer effects this repository
