### ISSUE TITLE
nbind vs gobject introspection

### ISSUE THREAD

**Issue by clayrisser** [Place1/react-native-gtk#14]
It's worth looking at gobject introspection. There's a good chance nbind is still a solid approach.

https://github.com/charto/nbind
https://wiki.gnome.org/Projects/GObjectIntrospection

node-gtk was built with gobject introspection.

https://github.com/WebReflection/node-gtk

**Comment by Place1** [comment]
node-gtk made use of glib's additional event source apis to nest node's libuv event loop. This basically meant both loops run in the same thread, with GTK's look driving node's loop. I actually implemented this approach in gtk-node in the past, but had issues with nodejs microtasks not being run.

this background is important because app.run() is a blocking call in gtk (it runs the mainloop) and we can't block node's loop. seeing how gjs and seed do bindings might be useful

**Comment by Place1** [comment]
This file from `node-gir` gives a good idea of how GI works:
https://github.com/creationix/node-gir/blob/master/src/namespace_loader.cc#L39

I'm not sure how the GI approach deals with glib's main loop blocking the node event loop. Other JS engines that have GI support like GJS and Seed both don't have the concept of setTimeout i believe (gjs definitely doesn't) and instead applications must use `g_idle_add()` to achieve this functionality using the glib main loop. In a nodejs environment this is problematic.

**Comment by Place1** [comment]
update:

i've been hacking on [node-gir](https://github.com/creationix/node-gir) today and i've made some good progress. I've got it compiling on Node 8 and the examples are running (including GTK)! And i've ported [node-gtk's glib event loop integration](https://github.com/WebReflection/node-gtk/blob/master/src/loop.cc) as well. Then I extended the event loop integration to run Nodejs Microtasks so that `process.nextTick()` and Promises work!

There's still a bunch of compiler warnings but i'm considering the GI approach instead.

edit:
here's a link to my fork of node-gir https://github.com/Place1/node-gir

try this:
```
git clone https://github.com/Place1/node-gir
cd node-gir
npm install
node ./examples/gtk_test.js
```

**Comment by harisvsulaiman** [comment]
@Place1 Seems like https://github.com/yue/node-gui has some tricks to solve the blocking thread issue.

**Comment by Place1** [comment]
@harisvsulaiman thanks for this! they seem to have a much cleaner solution for the multithreaded approach! I'd be keen to use something more like that but `node-gir` is proving like it's the best way forward in many ways, namely, with GI bindings you can use pretty much any library from the gnome world which is very beneficial and even for GTK, it means we'll have more finished faster.

**Comment by Place1** [comment]
I'm closing this issue in favour of gobject introspection.
